# Copyright 2024 Google LLC
#
# This is “Software” that is licensed under the “General Software” section of
# the Service Specific Terms (https://cloud.google.com/terms/service-terms) for
# usage in accordance with the following “Scope of Use”: This file may only be
# used on an Anthos cluster, including any associated ci/cd use. “Anthos
# cluster” is defined as “A Cluster (of any kind) registered to a fleet project
# where the Anthos API is enabled”.
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredAnnotations
metadata:
  name: cis-gke-v1.4.0-require-ingress.class-gce
  labels:
    policycontroller.gke.io/bundleName: cis-gke-v1.4.0
  annotations:
    policycontroller.gke.io/bundleVersion: 202402.0-preview
    policycontroller.gke.io/constraintData: |-
      "{
        bundleName: 'cis-gke-v1.4.0',
        bundleDisplayName: 'CIS GKE Benchmark v1.4.0',
        bundleLink: 'https://cloud.google.com/anthos-config-management/docs/how-to/using-cis-gke-v1.4',
        bundleVersion: '202402.0-preview',
        bundleDescription: 'Use the CIS GKE Benchmark 1.4.0 policy bundle with Policy Controller to evaluate the compliance of your cluster resources against the CIS GKE Benchmark v1.4.0, which is a set of recommendations for configuring GKE to support a robust security posture.',
        controlNumbers: '[5.6.8]',
        severity: 'UNSPECIFIED',
        description: 'Requires that all Ingress objects have a `kubernetes.io/ingress.class: "gce"` annotation.',
        remediation: 'Every Ingress object requires a `kubernetes.io/ingress.class: "gce"` annotation. Check Ingress objects and add a `kubernetes.io/ingress.class: "gce"` annotation. See "Using Google-managed SSL certificates" for more information: https://cloud.google.com/kubernetes-engine/docs/how-to/managed-certs',
        minimumTemplateLibraryVersion: '1.12.0',
        constraintHash: '56c5a1a98a68a291ab16bffc11493cce5bc932892a9778648f123eb654d31bcf'
      }"
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups:
          - extensions
          - networking.k8s.io
        kinds:
          - Ingress
  parameters:
    message: 'All Ingress objects must have a `kubernetes.io/ingress.class: "gce"` annotation'
    annotations:
      - key: kubernetes.io/ingress.class
        allowedRegex: ^gce$
