# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: AsmIngressgatewayLabel
metadata:
  name: asm-policy-v0.0.1-asm-ingressgateway-label
  labels:
    policycontroller.gke.io/bundleName: asm-policy-v0.0.1
  annotations:
    policycontroller.gke.io/constraintData: |
      "{
        bundleName: 'asm-policy-v0.0.1',
        bundleDisplayName: 'Anthos Service Mesh v0.0.1',
        bundleLink: 'https://cloud.google.com/anthos-config-management/docs/how-to/using-asm-security-policy',
        bundleVersion: '202310.0',
        bundleDescription: 'Use the ASM Policy v0.0.1 policy bundle with Policy Controller to evaluate the compliance of your clusters running Anthos Service Mesh against service mesh security best practices.',
        controlNumbers: '[1.1.1]',
        severity: 'UNSPECIFIED',
        description: 'Enforce the istio ingressgateway label usage only on ingressgateway pods.',
        remediation: 'Remove istio:ingressgateway label from the non ingressgateway pods.',
        minimumTemplateLibraryVersion: '1.11.2'
      }"
    policycontroller.gke.io/bundleVersion: "202310.0"
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
