# Copyright 2023 Google LLC
#
# This is “Software” that is licensed under the “General Software” section of
# the Service Specific Terms (https://cloud.google.com/terms/service-terms) for
# usage in accordance with the following “Scope of Use”: This file may only be
# used on an Anthos cluster, including any associated ci/cd use. “Anthos
# cluster” is defined as “A Cluster (of any kind) registered to a fleet project
# where the Anthos API is enabled”.
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sEnforceCloudArmorBackendConfig
metadata:
  name: pci-dss-v3.2.1-enforce-cloudarmor-backendconfig
  labels:
    policycontroller.gke.io/bundleName: pci-dss-v3.2.1
  annotations:
    policycontroller.gke.io/constraintData: |
      "{
        bundleName: 'pci-dss-v3.2.1',
        bundleDisplayName: 'PCI DSS v3.2.1',
        bundleLink: 'https://github.com/GoogleCloudPlatform/acm-policy-controller-library/tree/master/anthos-bundles/pci-dss-v3.2.1',
        bundleVersion: '202310.0',
        bundleDescription: 'Use the PCI DSS v3.2.1 policy bundle with Policy Controller to evaluate the compliance of your cluster resources against some aspects of the Payment Card Industry (PCI) Data Security Standard (DSS) v3.2.1.',
        controlNumbers: '[6.5, 6.6]',
        severity: 'UNSPECIFIED',
        description: 'Enforces Google Cloud Armor configuration on `BackendConfig` resources.',
        remediation: 'Google Cloud Armor is required on all `BackendConfig` resources. Set a valid `spec.securityPolicy.name` on each `BackendConfig` resource. See "Google Cloud Armor Ingress security policy" for more information: https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#cloud_armor',
        minimumTemplateLibraryVersion: '1.14.0'
      }"
    policycontroller.gke.io/bundleVersion: "202310.0"
spec:
  enforcementAction: dryrun
